# TRY/EXCEPT/FINALLY/ELSE
Существуют несколько типов [[Exception]] один них [[ValueError]]
```python
try: 
	int('hello')
except 
	ValueError as error: print('ValueError')
except 
	NameError: print('NameError')
```
Если не парится насчет всех исключений, которые существуют, то просто пишем
```python
except Exception:
	print('error')
```
Существует блок finally, который будет выполняться всегда
```python
try:
	pass
except:
	pass
finally:
	pass
```
Также существует блок else, который выполнятся только тогда, когда выполнился блок try
# RAISE

Raise вызывает ошибку
```python
raise ValueError('big problem')
#OR
raise ValueError
```
Также если используем try и except.
```python
try:
	[1,2,3][15]
except KeyError as error:
	print(repr(error))
	raise TypeError('Ошибка типа') from None
```
Без from None выводились бы две ошибки. Сначала error а потом которая в raise. С конструкцией from None выводится только raise

Зачеркнутые исключение это специфические классы исключения, основной из них это exception, который является родителям всех последующих исключений.

**Все исключения являются [[Классы]]**
# Вывод

Try/except/finally/else активно используется в дагах. Raise я пока не использовал в дагах, но звучит интересно, допустим чтобы вызвать самому ошибку и увидеть это, а не просто return. Пользовательские исключения я бы сказал это чисто для приложений всяких, в дагах им место особо как-будто нету. По сути это полезно применения в работе, но больше всего оно используется при написания приложения, то есть в DAG-ах оно особо не применимо.